### ISSUE TITLE
fix css relative paths in makedirlists()

### ISSUE THREAD

**Issue by jsav0** [haydenhv/staw#1]
The `$CSSPATH` and `$LIBPATH` inside of `makedirlists()` has one incorrect placement of slashes ("/") 
As a result, the index listing pages aren't as "pretty" as they could be. (this is only true for nested hierarchies)

Example:
Currently the relative paths are outputted into the `<head>` as:  `../../..css//dirlist.css`
But they should be: `../../../css/dirlist.css`

Here are the affected lines: (of the master branch)
`413                                         CSSPATH="../${DIRPATH}css/"`
`414                                         LIBPATH="../${DIRPATH}lib/conf/"`

Solution: (move the slash)
`413                                         CSSPATH="../${DIRPATH}/css"`
`414                                         LIBPATH="../${DIRPATH}/lib/conf"`

This is my first time submitting an issue so consider this a test.

**Comment by haydenhv** [comment]
Now fixed: https://github.com/haydenhv/staw/commit/58ca15b6a60a4bd8eebda6fbd2ef9b3b6d7a3eb2
